name: parse_this pre-submit queues

on:
  pull_request:
    branches:
      - "*"

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v2
    - name: set up python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: black formatter
      uses: psf/black@stable
      with:
        options: "--check --verbose"
        src: "./parse_this ./test"
    - name: lint with flake8
      run: |
        flake8 parse_this test --count --show-source --statistics
    - name: test with pytest
      run: |
        pytest --cache-clear --cov=parse_this --no-cov-on-fail test/ > pytest-coverage.txt
