name: parse_this publish package to pypi

on:
  push:
    branches:
      - master

jobs:
  publish:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
        - uses: actions/checkout@v2
        - name: set up Python
          uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python-version }}
        - name: install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install build
        - name: build package
          run: python -m build
        - name: publish package
          uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
          with:
            user: __token__
            password: ${{ secrets.PYPI_API_TOKEN }}
